server:
  port: 9000

spring:
  kafka:
    streams:
      properties:
        default:
          key.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
          value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
      group_id: group-id
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
  application:
    name: alex-streams-avro

app:
  topic: users